image: node:carbon

stages:
  - build
  - publish

build:
  stage: build
  script:
    - yarn
    - yarn build
  artifacts:
    paths:
      - package.json
      - README.md
      - LICENSE
      - dist/
      - docs/

publish:
  stage: publish
  script:
    - echo "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}" >> ~/.npmrc
    - npm publish --access public
  when: manual
  only:
    - master

publish-docs:
  stage: publish
  script:
    - yarn
    - ./ci-scripts/publish-tsdocs.sh sdk-react-native
  when: manual
  only:
    - master

