image: node:carbon

stages:
  - build
  - publish

build:
  stage: build
  script:
    - lerna bootstrap
    - yarn build

publish:
  stage: publish
  script:
    - echo "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}" >> ~/.npmrc
    - lerna bootstrap
    - lerna publish
  when: manual
  only:
    # Run only on tags with semantic versioning
    - ^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(-(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(\.(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*)?(\+[0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*)?$
  except:
    # And never run on branches
    - branches

