image: mitterio/build-image:stretch-standard-gcp

stages:
  - build
  - publish

before_script:
  - source ~/.nvm/nvm.sh
  - nvm use 8

build:
  stage: build
  script:
    - lerna bootstrap
    - lerna run build
  except:
    - /^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(-(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(\.(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*)?(\+[0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*)?$/

publish:
  stage: publish
  variables:
    GIT_STRATEGY: clone
    GIT_CHECKOUT: "false"
  script:
    - git checkout master
    - lerna bootstrap
    - git reset --hard
    - echo "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}" >> ~/.npmrc
    - echo "unsafe-perm = true" >> ~/.npmrc
    - lerna run build
    - lerna publish from-package --yes --no-verify-access
  only:
    # Run only on tags with semantic versioning
    - /^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(-(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(\.(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*)?(\+[0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*)?$/
  except:
    # And never run on branches
    - branches

