image: node:carbon

stages:
  - build
  - publish

build:
  stage: build
  script:
    - npm install -g lerna
    - lerna bootstrap
    - lerna run build

publish:
  stage: publish
  script:
    - npm install -g lerna
    - echo "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}" >> ~/.npmrc
    - lerna bootstrap
    - lerna publish --no-push --no-git-tag-version --no-git-reset
  only:
    # Run only on tags with semantic versioning
    - /^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(-(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(\.(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*)?(\+[0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*)?$/
  except:
    # And never run on branches
    - branches

