image: node:carbon

stages:
  - build
  - publish

build:
  stage: build
  script:
    - echo "//registry.npmjs.org/:_authTokne=${NPM_AUTH_TOKEN}" >> ~/.npmrc
    - cat ~/.npmrc
    - yarn
    - yarn build
  artifacts:
    paths:
      - package.json
      - README.md
      - LICENSE
      - dist/

publish:
  stage: publish
  script:
    - echo "//registry.npmjs.org/:_authTokne=${NPM_AUTH_TOKEN}" >> ~/.npmrc
    - npm publish --access public
  only:
    - master

